version: "3"
services: 
  api-gateway:
    container_name: api-gateway
    image: choudang/BE_tiki/api-gateway:latest
    build: ./BE_tiki/api-gateway 
    ports:
      - 8080:8080
    networks:
      - node-network

  identity-service:
    container_name: identity-service
    image: choudang/BE_tiki/identity-service:latest
    build: ./BE_tiki/identity-service
    networks:
      - node-network

  notification-service:
    container_name: notification-service
    image: choudang/BE_tiki/notification-service:latest
    build: ./BE_tiki/notification-service 
    networks:
      - node-network

  payment-service:
    container_name: payment-service
    image: choudang/BE_tiki/payment-service:latest
    build: ./BE_tiki/payment-service
    networks:
      - node-network

  product-service:
    container_name: product-service
    image: choudang/BE_tiki/product-service:latest
    build: ./BE_tiki/product-service
    networks:
      - node-network

  tiki_main:
    container_name: tiki-main
    image: choudang/tiki-main:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

networks:
  node-network:
    external: true # sử dụng mạng có sẵn trước đó

# docker-compose up -d